# Generated by Django 2.0.4 on 2018-04-21 14:33

from django.db import migrations


def add_toppings(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Topping = apps.get_model('api', 'Topping')
    toppings = ['cheese', 'tuna', 'eggplant', 'onions', 'avocado', 'tomatos']
    for topping in toppings:
        new_top = Topping.objects.create(name=topping)
        new_top.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_toppings),

    ]
